GET http://localhost:3000/mahasiswa

###
GET http://localhost:3000/mahasiswa/3

###
POST  http://localhost:3000/mahasiswa
Content-Type: application/json

{
    "name": "sueb",
    "nim": 323
}

###

PATCH   http://localhost:3000/mahasiswa/1
Content-Type: application/json

{
    "name": "mahasiswa updated",
    "nim": 123
}

###
DELETE http://localhost:3000/mahasiswa/1