GET http://localhost:5000/mahasiswa

###
GET http://localhost:5000/mahasiswa/3

###
POST  http://localhost:5000/mahasiswa
Content-Type: application/json

{
    "name": "jumari",
    "nim": 999
}

###

PATCH   http://localhost:5000/mahasiswa/1
Content-Type: application/json

{
    "name": "mahasiswa updated",
    "nim": 123
}

###
DELETE http://localhost:5000/mahasiswa/1